name: TERRAFORM PROJ

on:
  push:
    branches: [ master ]
    #tags:
     # - v.**

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn package
    - name: deploy into tomcat
      run: curl -v -u ${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASS }} -T /home/ec2-user/actions-runner/_work/spring3-mvc-maven-xml-hello-world/spring3-mvc-maven-xml-hello-world/target/spring3-mvc-maven-xml-hello-world-1.2.war 'http://65.2.63.249:8080/manager/text/deploy?path=/github_action_spring1&update=true'

